---
name: General CI
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: ghcr.io
      IMAGE_NAME: oldtyt/docker-flake8
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
      - name: Build image
        id: docker-build
        run: >-
          docker build
          -t $IMAGE_NAME
          -t $REPOSITORY_URL/$IMAGE_NAME:latest .
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Image
        id: docker-push
        run: docker push --all-tags $REPOSITORY_URL/$IMAGE_NAME
